import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 1,
    name: "Alicante",
    href: "#",
    image: "/images/delegations/alicante.png",
    imageLight: "/images/delegations/alicante.png",
  },
  {
    id: 2,
    name: "Bizkaia",
    href: "#",
    image: "/images/delegations/bizkaia.png",
    imageLight: "/images/delegations/bizkaia.png",
  },
  {
    id: 3,
    name: "Cantabria",
    href: "#",
    image: "/images/delegations/cantabria.png",
    imageLight: "/images/delegations/cantabria.png",
  },
  {
    id: 4,
    name: "Dominica",
    href: "#",
    image: "/images/delegations/dominica.png",
    imageLight: "/images/delegations/dominica.png",
  },
  {
    id: 5,
    name: "Filipinas Cebu",
    href: "#",
    image: "/images/delegations/cebu.png",
    imageLight: "/images/delegations/cebu.png",
  },
  {
    id: 6,
    name: "Extremadura",
    href: "#",
    image: "/images/delegations/extremadura.png",
    imageLight: "/images/delegations/extremadura.png",
  },
  {
    id: 7,
    name: "Gipuzkoa",
    href: "#",
    image: "/images/delegations/gipuzkoa.png",
    imageLight: "/images/delegations/gipuzkoa.png",
  },
  {
    id: 8,
    name: "Girona",
    href: "#",
    image: "/images/delegations/girona.png",
    imageLight: "/images/delegations/girona.png",
  },
  {
    id: 9,
    name: "Filipinas",
    href: "#",
    image: "/images/delegations/filipinas.png",
    imageLight: "/images/delegations/filipinas.png",
  },
  {
    id: 10,
    name: "La Rioja",
    href: "#",
    image: "/images/delegations/larioja.png",
    imageLight: "/images/delegations/larioja.png",
  },
  {
    id: 11,
    name: "Leon",
    href: "#",
    image: "/images/delegations/leon.png",
    imageLight: "/images/delegations/leon.png",
  },
  {
    id: 12,
    name: "Lleida",
    href: "#",
    image: "/images/delegations/lleida.png",
    imageLight: "/images/delegations/lleida.png",
  },
  {
    id: 13,
    name: "Malaga",
    href: "#",
    image: "/images/delegations/malaga.png",
    imageLight: "/images/delegations/malaga.png",
  },
  {
    id: 14,
    name: "Navarra",
    href: "#",
    image: "/images/delegations/navarra.png",
    imageLight: "/images/delegations/navarra.png",
  },
  {
    id: 15,
    name: "Recoletos Youth",
    href: "#",
    image: "/images/delegations/recoletos.png",
    imageLight: "/images/delegations/recoletos.png",
  },
  {
    id: 16,
    name: "Zaragoza",
    href: "#",
    image: "/images/delegations/zaragoza.png",
    imageLight: "/images/delegations/zaragoza.png",
  },
];

export default brandsData;
